import { ChakraProvider } from '@chakra-ui/react';
import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Poppins } from 'next/font/google';

const inter = Poppins({
  subsets: ['latin'],
  weight: '100'
})

export const metadata = {
  title: `Anisa's Porto`,
  description: 'Generated by create next app and by myself',
  image: './icon-a.png',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
  )
}
